### PR TITLE
build: add bumpversion script

### PR DESCRIPTION
**Pull request by hoodie**

### CODE REVIEW

**Review by TobTheRock — APPROVED** [review]
Maybe we could put that script in a subfolder `scripts`. But no strong opinion here.

**Comment by TobTheRock** [comment]
`main` is a protected branch, I think I also disabled pushing by admins with **Do not allow bypassing the above settings** on the branch rules. Should we also add a github action running that script (optimal: when triggering a release) or change the settings for now? I haven't tried though so maybe we should practise with a new release ;)

**Comment by hoodie** [comment]
maybe we can investigate how to release from github actions instead

**Comment by hoodie** [comment]
a nice example might be found in tokio console: https://github.com/tokio-rs/console/blob/main/.github/workflows/release.yaml

**Comment by TobTheRock** [comment]
An action sounds like a good idea. Here some other existing actions (with examples) we could use:
    [elgohr/Github-Release-Action](https://github.com/elgohr/Github-Release-Action)
    [marvinpinto/action-automatic-releases](https://github.com/marvinpinto/action-automatic-releases)
    [softprops/action-gh-release](https://github.com/softprops/action-gh-release)
    [ncipollo/release-action](https://github.com/ncipollo/release-action)

**Comment by hoodie** [comment]
looks like this problem is solved now

**Pull request closed without merging**
